repos:
-   repo: https://github.com/python/black
    rev: 21.9b0
    hooks:
    -   id: black
        args: [--line-length=100]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
        name: trailing-whitespace-markdown
        types: [markdown]